### PR TITLE
Net: work around handling of empty PathAndQuery in `http`.

### LINKED ISSUE #97: unable to connect to sectigo
### Bug Overview

when attempting to connect to sectigo I get this:
2025/12/06 00:39:56 [warn] 1520#1520: directory update failed (cannot deserialize response (expected value at line 1 column 1)) while creating account for acme issuer "Sectigo"

The sectigo uri is https://acme.enterprise.sectigo.com   there is no /directory url 

We are using the sectigo Certificate Manager solution and have it connected to our AD CA.

I see an access.key file in the cache, but never anything else.  

### Expected Behavior

I should be able to connect and get certificates.

### Steps to Reproduce the Bug

config:

    resolver <dns server> ipv6=off valid=5s;
    acme_shared_zone zone=ngx_acme_shared:1M;

    acme_issuer Sectigo {
        uri https://acme.enterprise.sectigo.com;
        account_key ecdsa:256;   # or rsa:2048

        state_path /var/cache/nginx/acme;
        accept_terms_of_service;
        external_account_key <Account> /etc/nginx/ssl/private/Sectigo_acme.key;#
        challenge  tls-alpn-01;
    }

Server{
..
  acme_certificate Sectigo;

        ssl_certificate       $acme_certificate;

        ssl_certificate_key   $acme_certificate_key;

### Environment Details

runing on ubuntu 24.04
R36.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bavshin-f5**
An absolute http::uri::Uri with an empty but set PathAndQuery ("") will pretend that the path is "/" for comparison, display or HTTP request construction purposes. However, a relative URI constructed from such PathAndQuery will be empty.

A directory URI without a path (i.e. "https://example.com") thus resulted in an empty path in the request line and 400 Bad Request from the server.

Fixes #97.

### CODE REVIEW

File: src/net/http.rs [hunk 1]
```diff
@@ -107,18 +107,22 @@ impl HttpClient for NgxHttpClient<'_> {
         <B as Body>::Data: Send,
         <B as Body>::Error: StdError + Send + Sync,
     {
-        let uri = req.uri().clone();
+        const DEFAULT_PATH: http::uri::PathAndQuery = http::uri::PathAndQuery::from_static("/");
+
+        let path_and_query = req
+            .uri()
+            .path_and_query()
```
Comment (ensh63) [inline src/net/http.rs:114]: I haven't tested, but what if URI does not contain path but includes some query part: 'http://example.org?something=1' ?

Comment (bavshin-f5) [reply src/net/http.rs:114]: This actually works fine. The only broken scenario is when PathAndQuery is completely empty.

Relevant snippets from http (hyper uses `Display `impl for `http::uri::Uri `to write a request line):

```rust
    #[inline]
    pub fn path(&self) -> &str {
        if self.has_path() {
            self.path_and_query.path()
        } else {
            ""
        }
    }

    fn has_path(&self) -> bool {
        !self.path_and_query.data.is_empty() || !self.scheme.inner.is_none()
    }
```
